version: "3"

services:
  #------------------------------------------------------------------------------
  # Traefik proxy
  #------------------------------------------------------------------------------
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--pilot.token=${TRAEFIK_PILOT_TOKEN}"
      - "--experimental.devPlugin.goPath=/plugins/go"
      - "--experimental.devPlugin.moduleName=github.com/WLun001/i18nrewrite"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/plugins/go/src/github.com/WLun001/i18nrewrite"

  #------------------------------------------------------------------------------
  # whoami service
  #------------------------------------------------------------------------------

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=i18nrewrite"
      - "traefik.http.middlewares.i18nrewrite.plugin.dev.langCodes=['zh', 'en']"
